- name: set timezone {{ zone }}
  shell: timedatectl set-timezone {{ zone }}
  register: set_timezone
  changed_when: false

- name: set locale {{ keymap }}
  shell: localectl set-keymap {{ keymap }}
  register: set_locale
  changed_when: false

- name: install wget/git/libselinux-python
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - git
    - libselinux-python
    - epel-release
    - python-pip

- name: disable SELinux
  selinux: state=disabled

- name: remove firewalld
  yum: name=firewalld state=absent

- name: sysctl.conf vm.swappiness 1
  sysctl: name="vm.swappiness" value=1 state=present

- name: sysctl.conf disable ipv6
  sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1

- name: add alias
  shell: echo "alias lr='ls -lahtr'" >> /root/.bashrc

- name: nginx location config file directory
  file:
    path:  /root
    state: directory
    owner: root
    group: root
    mode: 0700

- name: generate SSH keys
  shell: ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
  args:
    creates: /root/.ssh/id_rsa

- name: generate ~/.ssh/authorized_kyes
  shell: touch ~/.ssh/authorized_kyes; chmod 600 ~/.ssh/authorized_kyes
