- name: set timezone {{ zone }}
  shell: timedatectl set-timezone {{ zone }}
  register: set_timezone
  changed_when: false

- name: set locale {{ keymap }}
  shell: localectl set-keymap {{ keymap }}
  register: set_locale
  changed_when: false

- name: install wget/git/libselinux-python
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - git
    - libselinux-python
    - epel-release
    - python-pip

- name: disable SELinux
  selinux: state=disabled

- name: remove firewalld
  yum: name=firewalld state=absent

- name: sysctl.conf vm.swappiness 1
  sysctl: name="vm.swappiness" value=1 state=present

- name: sysctl.conf disable ipv6
  sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1

- name: add alias
  shell: echo "alias lr='ls -lahtr'" >> /root/.bashrc
