- name: install GlusterFS repo
  yum: name=centos-release-gluster state=latest

- name: install GlusterFS and prerequisites of ColumnStore
  yum: name={{ item }} state=latest
  with_items:
    - boost
    - expect
    - perl
    - perl-DBI
    - openssl
    - zlib
    - libaio
    - rsync
    - net-tools
    - snappy
    - perl-DBD-MySQL
    - nmap
    - glusterfs
    - glusterfs-fuse
    - glusterfs-server
    - python-pip

- name: download ColumnStore 1.1.0 beta
  copy:
    src:  /vagrant/mariadb-columnstore-1.1.0-1-centos7.x86_64.rpm.tar.gz
    dest: /root
    mode: 0444

- name: extract ColumnStore 1.1.0 beta RPM tar ball
  unarchive:
    src:  /root/mariadb-columnstore-1.1.0-1-centos7.x86_64.rpm.tar.gz
    dest: /root/
    remote_src: yes

- name: remove existing MariaDB RPMs
  shell: yum -y remove mariadb-* MariaDB-*

- name: install RPMs
  shell: yum -y localinstall mariadb-columnstore-*.rpm
  args:
    chdir: /root

- name: enable/start glusterd service
  systemd: name=glusterd state=restarted enabled=True
