- include: mariadb-centos7.yml

- name: copy Galera configuration template {{ hostvars[inventory_hostname]["ansible_eth1"]["ipv4"]["address"] }}
  template: src=galera.cnf dest=/etc/my.cnf.d/

- name: bootstrap the Master node
  shell: galera_new_cluster
  when:  is_master

- name: enable/start MariaDB server on 2nd/3rd node
  systemd: name=mariadb state=started enabled=True
  when:    not is_master


- name: install MYSQL-python
  yum: name=MySQL-python state=present

- name: create maxuser(super) user
  mysql_user: name=maxuser host='% password=maxpwd priv='*.*:ALL' state=present

# - name: create maxadmin user
#   mysql_user: name=maxadmin host="%" password=maxpwd priv="*.*:SELECT,SHOW DATABASES" state=present

- name: copy .bash_history
  copy: src=bash_history dest=/root/.bash_history

- name: copy .mysql_history
  copy: src=mysql_history dest=/root/.mysql_history
