- name: set up MariaDB {{ mdb_version }} repository
  yum_repository:
    name:        mariadb
    description: MariaDB
    baseurl:     http://yum.mariadb.org/10.4/centos7-amd64
    gpgkey:      https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck:    1

- name: MariaDB {{ mdb_version }} RPM tar ball exists ?
  stat: path=/vagrant/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms.tar
  register: rpmtar

- name: rpmtar
  debug:
    msg: rpmtar {{ rpmtar.stat.exists }}

- name: unarchive RPM tarball
  unarchive:
    src:  /vagrant/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms.tar
    dest: /root

- name: install MariaDB server w/ yum -y localinstall
  shell: |
    yum -y localinstall MariaDB-server-{{ mdb_version }}-*.rpm \
                        MariaDB-client-{{ mdb_version }}-*.rpm \
                        MariaDB-common-{{ mdb_version }}-*.rpm \
                        MariaDB-compat-{{ mdb_version }}-*.rpm
  args:
    chdir: /root/mariadb-{{ mdb_version }}-rhel-7-x86_64-rpms
  when: rpmtar.stat.exists

- name: install MariaDB-server from remote repo
  yum: name=MariaDB-server state=latest update_cache=yes
  when: not rpmtar.stat.exists
