- hosts: all
  vars:
    locale: en_US.UTF-8
    keymap: jp106
    zone:   Asia/Tokyo
  sudo: yes
  user: vagrant
  roles:
    - common
    - server

- hosts: galera1:galera2:galera3
  vars:
    locale: en_US.UTF-8
    keymap: jp106
    zone:   Asia/Tokyo
  environment:
    http_proxy: 192.168.18.139:3128
    https_proxy: 192.168.18.139:3128
  sudo: yes
  user: vagrant
  roles:
    - galera

- hosts: maxscale
  vars:
    locale: en_US.UTF-8
    keymap: jp106
    zone:   Asia/Tokyo
  sudo: yes
  user: vagrant
  roles:
    - maxscale
