- hosts: all
  vars:
    locale: en_US.UTF-8
    keymap: jp106
    zone:   Asia/Tokyo
  become: yes
  user: vagrant
  roles:
    - common

- hosts: galera1
  become: yes
  user: vagrant
  roles:
    - galera

- hosts: galera2:galera3
  become: yes
  user: vagrant
  roles:
    - galera
    
- hosts: maxscale
  sudo: yes
  user: vagrant
  roles:
   - maxscale
