- hosts: all
  vars:
    locale: en_US.UTF-8
    keymap: jp106
    zone:   Asia/Tokyo
  become: yes
  user: vagrant
  roles:
    - common

- hosts: galera1:galera2:galera3
  environment:
    http_proxy: 192.168.18.1:3128
    https_proxy: 192.168.18.1:3128
  become: yes
  user: vagrant
  roles:
    - galera

- hosts: maxscale
  environment:
    http_proxy: 192.168.18.1:3128
    https_proxy: 192.168.18.1:3128
  sudo: yes
  user: vagrant
  roles:
    - maxcale
