- name: copy ~vagrant/.bash_history
  copy:
    src: bash_history
    dest: /home/vagrant/.bash_history
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: MariaDB Package Repository Setup
  shell: \
    curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | \
    sudo bash -s -- --mariadb-maxscale-version=2.3

- name: install MaxScale 2.3
  yum: name=maxscale state=latest update_cache=yes

- name: copy maxscale configuration
  copy: src=maxscale.cnf dest=/etc/maxscale.cnf

- name: copy ~/.bash_history
  copy: src=bash_history dest=/root/.bash_history

- name: enable/start MaxScale
  systemd: name=maxscale state=restarted enabled=True
